runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /styles
  static_dir: styles

- url: /.*
  script: main_page.app
